version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache -p ${GANACHE_PORT} -i ${NETWORK_ID}
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}

  contract-deployer:
    depends_on:
      - ganache
    build:
      context: ./blockchain
      args:
        - NETWORK_ID=${NETWORK_ID}

    volumes:
      - contracts:/blockchain/build/contracts

  dapp:
    build:
      context: ./dapp
    ports:
      - ${DAPP_PORT}:${DAPP_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NETWORK_ID=${NETWORK_ID}
      - PORT=${DAPP_PORT}
    volumes:
      - ./dapp:/dapp
      - contracts:/dapp/src/contracts

volumes:
  contracts:
    driver: local